// Snippets data - Auto-generated file
// DO NOT EDIT THIS FILE DIRECTLY - Changes may be overwritten

const snippetsData = [
    {
        "id": "snippet-1746140004108",
        "title": "fuckyou",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "function fuck(you) {  /** logic here **/}",
                "rawCode": "function fuck(you) {  /** logic here **/}"
            }
        ],
        "createdAt": "2025-05-01T22:53:50.359Z",
        "updatedAt": "2025-05-01T22:53:50.359Z"
    },
    {
        "id": "snippet-1746139461091",
        "title": "hirhgff",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "function hey(hi) {   /** logic **/ }",
                "rawCode": "function hey(hi) {   /** logic **/ }"
            }
        ],
        "createdAt": "2025-05-01T22:44:59.532Z",
        "updatedAt": "2025-05-01T22:44:59.532Z"
    },
    {
        "id": "snippet-1746138599069",
        "title": "hai",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "function hey(){  /** logic **/}",
                "rawCode": "function hey(){  /** logic **/}"
            }
        ],
        "createdAt": "2025-05-01T22:30:37.476Z",
        "updatedAt": "2025-05-01T22:30:37.485Z"
    },
    {
        "id": "snippet-1746084032744",
        "title": "lol",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "function lol(woah){   /** logic **/}",
                "rawCode": "function lol(woah){   /** logic **/}"
            }
        ],
        "createdAt": "2025-05-01T07:21:01.601Z",
        "updatedAt": "2025-05-01T07:21:01.601Z"
    },
    {
        "id": "snippet-1746083333994",
        "title": "testing",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "function test(){   /** logic here **/}",
                "rawCode": "function test(){   /** logic here **/}"
            }
        ],
        "createdAt": "2025-05-01T07:09:36.391Z",
        "updatedAt": "2025-05-01T07:09:36.391Z"
    },
    {
        "id": "snippet-1746083294965",
        "title": "test",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "test",
                "rawCode": "test"
            }
        ],
        "createdAt": "2025-05-01T07:08:23.582Z",
        "updatedAt": "2025-05-01T07:08:23.585Z"
    },
    {
        "id": "snippet-1746074312892",
        "title": "example",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "[object Promise]",
                "rawCode": "[object Promise]"
            }
        ],
        "createdAt": "2025-05-01T04:39:57.517Z",
        "updatedAt": "2025-05-01T04:39:57.517Z"
    },
    {
        "id": "snippet-1746074272347",
        "title": "heyeyey",
        "languages": [
            {
                "id": "javascript",
                "name": "JavaScript",
                "code": "[object Promise]",
                "rawCode": "[object Promise]"
            }
        ],
        "createdAt": "2025-05-01T04:37:59.249Z",
        "updatedAt": "2025-05-01T04:37:59.249Z"
    }
];
